# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sbb-container-jr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://jungreal.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1e7bde7b20e44a6290942ef19030a516 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3accc5b19f3049fab05643cdb5a64d30 }}
    
    - run: chmod 777 ./gradlew
      name: gradle file permission change
      
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jungreal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1e7bde7b20e44a6290942ef19030a516 }}/sbb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sbb-container-jr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a517c4cc7aee4b54b6bc0f65dfc794f5 }}
        images: 'jungreal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1e7bde7b20e44a6290942ef19030a516 }}/sbb:${{ github.sha }}'
